### ISSUE TITLE
[UserStory] Update Gradle from 5.6.3 to 8.4

### ISSUE THREAD

**Issue by ThomasD0213** [MetroCS/imagelab#115]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  contributor
**I want**  the build to use version 8.4 of Gradle
**so that**  I can build and test the product using a more current version of Gradle

## Acceptance Criteria
* build.gradle reflects the format of Gradle 8.4 build files
* the project successfully builds the product using Gradle version 8.4
* quality assessments (tests, style check, ...) run properly using Gradle version 8.4

## Supporting Information
My group in CS3350 chose to work on this project for the semester. In trying to set up this project on our machines, we had trouble getting gradle to work. In a LOT of trial and error we came to the conclusion that gradle would need to be updated before we could make any substantial progress. In addition to this, updating gradle will minimize technical debt. The primary stakeholder for this would be maintainers of the project, as this is more of a developer experience issue and less of an issue for the users.

### Depends On
N/A
### Dependents
N/A

**Comment by jody** [comment]
I appreciate the effort that went into tracking this down.

I think the title isn't quite appropriate. (It suggests that you are proposing to "upgrade gradle", which would be a different project.) On the other hand, the acceptance criteria are much more in line with what I assume to be the actual objective: updating the project so that it builds using Gradle 8.4.

_Q: Does the current version of the project build the product correctly using Gradle 5.6.3?_

In any event, an important first step is opening an issue with a request that the documentation specify which particular versions of Gradle are necessary for building and testing the product.

Here are some suggestions for updating this User Story:
- Modify the title to reflect what is actually being "upgraded"/changed
- In the user story, it's unclear why a "student" wants this change (especially with respect to the "technical debt" rationale)
- An appropriate stakeholder is a product "maintainer"
- Add the specific version number of Gradle to the third Acceptance Criteria (these are mutually independent specs)

**Comment by ThomasD0213** [comment]
> Q: Does the current version of the project build the product correctly using Gradle 5.6.3?

I haven't been able to successfully build on my machine, along with my team

> I think the title isn't quite appropriate. (It suggests that you are proposing to "upgrade gradle", which would be a different project.)

So this was actually a solution I was exploring, which was to create a new gradle project and migrate the code to this new gradle project.

>In the user story, it's unclear why a "student" wants this change (especially with respect to the "technical debt" rationale)
An appropriate stakeholder is a product "maintainer"

I'll make some changes to reflect these suggestions.

**Comment by jody** [comment]
I'd like to add this issue into the current project; just needs a revised title and story.

**Comment by jody** [comment]
Thank you!  I've updated the user story and acceptance criteria. Will add to the project task board.  Let me know if you want to work on resolving this issue.

**Comment by jody** [comment]
Closing this issue because closing #137 renders this no longer relevant.
