### ISSUE TITLE
Bug Report Gradle will not build

### ISSUE THREAD

**Issue by KaizenPool** [MetroCS/imagelab#123]
**Describe the bug**
When I try to ./gradlew build in terminal it says there is a bug(see screenshot for details
<img width="569" alt="Screenshot 2023-10-31 at 12 26 05 PM" src="https://github.com/MetroCS/imagelab/assets/143539698/8e159eff-75f3-4646-9bcb-faab0aa24a50">

**To Reproduce**
1. Go to the imagelab directory
2. enter the command ./gradlew .build it does not build and creates an error
3. See error (see screenshot)

**Expected behavior**
The project should build using the gradle build tools to automate the project, and not crash.

**Screenshots**

**Desktop (please complete the following information):**
 using MacOS ventura 13.6

**Additional context**
The program can work using the java -cp ".:imagelab.jar" Run but it does not build with gradle. (using either the terminal or running it through intelliJ)

Java -cp ".:imagelab.jar" Run

**Comment by CameronSpear** [comment]
I would like to be added to this issue

**Comment by ramahali** [comment]
Can you add me to this issue

**Comment by jody** [comment]
Any progress on this effort?

**Comment by ramahali** [comment]
I think mine builds successfully. I updated the new version of Gradle, and it seems to be working. However, I am not too sure about it. I just need to check with you @jody

**Comment by jody** [comment]
> I think mine builds successfully. I updated the new version of Gradle, and it seems to be working. However, I am not too sure about it. I just need to check with you @jody

@ramahali Please post a transcript of your build session, including the info about which version of Gradle you are using.  Thank you!

**Comment by jody** [comment]
It appears that building with an IDE that has the ability to use previous versions of Gradle still works. However, that's not satisfactory if the project is to go forward.

Since it is relatively straightforward to configure an Apache Ant build for this project and given Ant's stability, I am establishing the default build tool to be Apache Ant.

Since Gradle is no longer the primary build tool, I will also close all issues associated with failures due to Gradle.

**Comment by jody** [comment]
Closing this issue because closing #137 renders this no longer relevant.
