### ISSUE TITLE
DevelopementConditions.MD accuracy

### ISSUE THREAD

**Issue by KaizenPool** [MetroCS/imagelab#131]
# User Story
### Essential components
- [ ] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  contributor
**I want**  to know how the project is build
**so that**  I know how to test the program

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* The convention must tell how the user/developer can execute the code
* It must be clear that this way works
*  Update the conventions specific to imagelab

### Scenario 1
**Given**  Current Convention that has how to work the code
**when**  read the the convention I will know how to build the program. 
**then**  the user will know how to build the programmer.

## Supporting Information
look at the DevelopmentConventions.MD update since there is no working method to build the code

**Comment by jody** [comment]
@KaizenPool says, "look at the DevelopmentConventions.MD update since there is no working method to build the code"

The [README](https://github.com/MetroCS/imagelab#readme) appears to have the desired information under the heading [Build Instructions](https://github.com/MetroCS/imagelab#build-instructions).

Please review the existing documentation and identify specific changes and additions.
