### ISSUE TITLE
[UserStory] sound package checkstyle report

### ISSUE THREAD

**Issue by GeoffZC** [MetroCS/imagelab#34]
# User Story
### Essential components
- [X] Title describes the story
- [X] Stakeholder type is identified
- [X] Outcome is described
- [X] Rationale is explicit
- [X] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  contributor  
**I want**  the checkstlye errors in the sound package to be fixed  
**so that**  the code adheres to coding style conventions.  

## Acceptance Criteria
Build runs without any checkstyle errors in the sound package. 

*Zero checkstyle errors for the sound package.
*Full JavaDoc documentation in the sound package.
*Code runs without errors.  

## Supporting Information
_(Relevant information, context, resources)_

### Depends On
_(Issues on which this story depends)_
### Dependents
Issue #32 dependent on completion of this issue.

**Comment by jody** [comment]
The file attachment (main.zip) isn't viewable in GitHub and there's no context explaining what that file is or why it is there.
  
I think this is part of an epic, so that "parent" issue should be identified (probably as a Dependent).

Since this specifically mentions "sound" in the title, the body of the User Story (e.g., Outcome, Acceptance Criteria) should likewise reference the "sound" package.

**Comment by GeoffZC** [comment]
New pull request #41
