### ISSUE TITLE
[UserStory] _Documentation does not describe the available filters_

### ISSUE THREAD

**Issue by ShayneKaiser** [MetroCS/imagelab#68]
# User Story
### Essential components
- [ ] Title describes the story
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
**As a**  user
**I want**    to be able to see what filters are currently available before I run ImageLab
**so that** new users can better identify the functionality of the program.  

## Acceptance Criteria

* There should be a list of and description of the available filters in the README and ImageLab wiki.

**Comment by jody** [comment]
Students are expected to access and read the source code files. There is thus a way for users to see what filters are currently available before running imageLab. There's no indication why the documentation in the filters' source code is insufficient.

Teachers may wish to add or remove filters depending on their pedagogical needs. Documenting specific instances of filters in a distributed README for all seems to add extra work to those users without provide sufficient benefit.

The acceptance criteria presumes that end-users are an intended audience of the README and the wiki. Since there are multiple README files, it is unclear which README is intended. At the top level, both of those resources are considered development documentation, so _end users_ aren't expected to access them as part of normal usage.

Closing this. If there's a more specific issue please re-open or create a new issue.
