### ISSUE TITLE
[UserStory] Window commands/buttons

### ISSUE THREAD

**Issue by alope151** [MetroCS/imagelab#9]
# User Story
### Essential components
- [x] Title describes the story
- [x] Stakeholder type is identified
- [x] Outcome is described
- [x] Rationale is explicit
- [x] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a user of Imagelab 
I want to be able to control auxiliary image panels
so that the window controls match the main app panel.

## Acceptance Criteria
_(Rules or scenarios are acceptable formats.)_

* _Rule 1_ 
Each auxiliary window has a minimize, maximize, and close button similar to the main window.

**Comment by alope151** [comment]
If this is acceptable, please assign to me (@alope151) and @BdwinE

**Comment by jody** [comment]
Minor wording change of Acceptance Criteria.

**Comment by jody** [comment]
I believe that I may have tracked the problem solution down to the [DisplayImage](../blob/master/imagelab/DisplayImage.java) class, specifically the combination of [setUndecorated](https://github.com/MetroCS/imagelab/blob/2b119e745f81a4dc4e3d7dc6262c3f0b0c13fbd5/imagelab/DisplayImage.java#L62) and [setBackground](https://github.com/MetroCS/imagelab/blob/2b119e745f81a4dc4e3d7dc6262c3f0b0c13fbd5/imagelab/DisplayImage.java#L63).

To show the decorations (close, minimize, maximize), the _undecorated_ property must be set to false:
```java
setUndecorated(false);
```

However, since the frame is now decorated, the alpha channel of the background color cannot be set to any value other than 255.  Thus the original line
https://github.com/MetroCS/imagelab/blob/2b119e745f81a4dc4e3d7dc6262c3f0b0c13fbd5/imagelab/DisplayImage.java#L63
will now throw an exception
```java.lang.IllegalArgumentException: Color parameter outside of expected range: Alpha```

This can be remedied by setting the alpha channel value to 255:
```java
setBackground(new Color(255,255,255,255));
```
or, more simply, by removing the alpha value from the Color object constructor call:
```java
setBackground(new Color(255,255,255));
```

So it seems that this issue can be addressed in the existing repository by changing these two lines:
https://github.com/MetroCS/imagelab/blob/2b119e745f81a4dc4e3d7dc6262c3f0b0c13fbd5/imagelab/DisplayImage.java#L62-L63
to
```java
setUndecorated(false);
setBackground(new Color(255,255,255));
```

Note that I have only explored this avenue and _I have not adequately tested this solution approach._

**Comment by alope151** [comment]
I went ahead and implemented some changes that allow the functions to work on all the operating systems available to our group. We will work on updating documentation and testing before submitting a pull request!

**Comment by alope151** [comment]
Auxiliary windows now include window function buttons (min, max, exit). See included screenshot.
<img width="335" alt="TestScreenShot" src="https://user-images.githubusercontent.com/55638612/70184965-289d4880-16a6-11ea-8d20-7943deeb0782.png">

**Comment by jody** [comment]
PR #20 has too many changes unrelated to this User Story so cannot be merged.

**Comment by alope151** [comment]
Pull request updated
